const DENOMS=[500000,200000,100000,50000,20000,10000,5000,2000,1000,500];let active=0;
const fmt=n=>Number(n||0).toLocaleString("vi-VN"), parse=v=>Number(String(v||"").replace(/[^\d-]/g,""))||0, rows=document.getElementById("cashRows");
function renderRows(){rows.innerHTML=DENOMS.map(d=>`<tr><td>${label(d)}</td><td><input data-denom="${d}" inputmode="numeric" value="0"></td><td id="sum-${d}">0</td></tr>`).join("");rows.querySelectorAll("input").forEach(i=>i.addEventListener("input",calc));calc();}
function label(d){return d>=1000?d/1000+"k":d}
function getInput(d){return rows.querySelector(`input[data-denom="${d}"]`)}
function qty(d){return parse(getInput(d)?.value)}
function setQty(d,v){const i=getInput(d); if(i)i.value=Math.max(0,v); calc();}
function renderMobile(){const d=DENOMS[active];document.getElementById("currentDenom").textContent=label(d);document.getElementById("currentQty").textContent=qty(d);}
function calc(){let total=0;rows.querySelectorAll("input").forEach(i=>{const d=Number(i.dataset.denom), q=parse(i.value), s=d*q;total+=s;document.getElementById("sum-"+d).textContent=fmt(s);});document.getElementById("countTotal").textContent=fmt(total);const sys=parse(document.getElementById("systemTotal").value);const diff=total-sys;document.getElementById("diffTotal").textContent=fmt(diff);document.getElementById("diffTotal").style.color=diff===0?"#ffe98b":(diff>0?"#00d9ff":"#ff6b6b");renderMobile();}
document.getElementById("systemTotal").addEventListener("input",calc);document.getElementById("clearBtn").onclick=()=>{rows.querySelectorAll("input").forEach(i=>i.value=0);document.getElementById("systemTotal").value="";calc();};document.getElementById("saveBtn").onclick=()=>{const item={time:new Date().toLocaleString("vi-VN"),total:document.getElementById("countTotal").textContent,system:document.getElementById("systemTotal").value,diff:document.getElementById("diffTotal").textContent};const list=JSON.parse(localStorage.getItem("tk_cash_history")||"[]");list.unshift(item);localStorage.setItem("tk_cash_history",JSON.stringify(list.slice(0,50)));renderHistory();alert("Đã lưu lịch sử.");};document.getElementById("historyBtn").onclick=()=>{document.getElementById("historyBox").classList.toggle("hidden");renderHistory();};function renderHistory(){const list=JSON.parse(localStorage.getItem("tk_cash_history")||"[]");document.getElementById("historyList").innerHTML=list.length?list.map(x=>`<div class="history-item"><b>${x.time}</b><br>Tổng: ${x.total} • Hệ thống: ${x.system||0} • Chênh: ${x.diff}</div>`).join(""):"Chưa có lịch sử.";}
document.getElementById("modeBtn").onclick=()=>document.body.classList.toggle("mobile-mode");document.getElementById("prevDenom").onclick=()=>{active=(active-1+DENOMS.length)%DENOMS.length;renderMobile();};document.getElementById("nextDenom").onclick=()=>{active=(active+1)%DENOMS.length;renderMobile();};document.getElementById("minusBtn").onclick=()=>setQty(DENOMS[active],qty(DENOMS[active])-1);document.getElementById("plusBtn").onclick=()=>setQty(DENOMS[active],qty(DENOMS[active])+1);
document.getElementById("voiceBtn").onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert("Trình duyệt chưa hỗ trợ nhập giọng nói.");const r=new R();r.lang="vi-VN";r.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();const m=t.match(/(\d+)\s*(nghìn|k|trăm|triệu)?\D+(\d+)/);if(m){let d=Number(m[1]);if(m[2]&&m[2].includes("triệu"))d*=1000000;else if(m[2]&&(m[2].includes("nghìn")||m[2].includes("k")))d*=1000;const found=DENOMS.find(x=>x===d);if(found)setQty(found,Number(m[3]));}};r.start();};renderRows();