let books=[], current=null;const grid=document.getElementById("bookGrid"), cats=document.getElementById("categoryList");
const sample=[{title:"Hướng dẫn TK Reader",category:"Hướng dẫn",type:"txt",content:"Upload TXT/PDF/ảnh truyện hoặc nhập URL Apps Script đọc Google Drive. Nếu bạn thêm truyện vào Drive, bấm Làm mới Drive để tự cập nhật thư viện."}];
function save(){localStorage.setItem("tk_reader_books",JSON.stringify(books.filter(b=>!b.fileObj)));}
function load(){try{books=[...sample,...JSON.parse(localStorage.getItem("tk_reader_books")||"[]")];}catch(e){books=[...sample];}render();}
function render(cat="Tất cả"){const categories=["Tất cả",...new Set(books.map(b=>b.category||"Khác"))];cats.innerHTML=categories.map(c=>`<button class="${c===cat?"active":""}" data-cat="${c}">${c}</button>`).join("");grid.innerHTML=books.filter(b=>cat==="Tất cả"||(b.category||"Khác")===cat).map((b,i)=>`<div class="book-card" data-i="${books.indexOf(b)}"><b>${b.title}</b><em>${b.category||"Khác"} • ${b.type||"file"}</em></div>`).join("");}
cats.onclick=e=>{const b=e.target.closest("button");if(b)render(b.dataset.cat);};grid.onclick=e=>{const c=e.target.closest(".book-card");if(c)openBook(books[Number(c.dataset.i)]);};
document.getElementById("localFiles").onchange=async e=>{for(const file of e.target.files){const ext=file.name.split(".").pop().toLowerCase();let book={title:file.name.replace(/\.[^.]+$/,""),category:ext==="pdf"?"PDF":(["jpg","jpeg","png","webp"].includes(ext)?"Truyện tranh":"Truyện chữ"),type:ext};if(ext==="txt"||ext==="html"||ext==="htm")book.content=await file.text();else book.url=URL.createObjectURL(file);books.unshift(book);}save();render();};
document.getElementById("loadDriveBtn").onclick=async()=>{const url=document.getElementById("driveApi").value.trim();if(!url)return alert("Nhập Apps Script / JSON URL trước.");localStorage.setItem("tk_reader_drive_url",url);try{const res=await fetch(url+"?t="+Date.now());const data=await res.json();const arr=Array.isArray(data)?data:(data.files||data.books||[]);books=[...sample,...arr.map(x=>({title:x.name||x.title,category:x.category||x.folder||"Drive",type:x.type||"drive",url:x.url||x.webContentLink||x.downloadUrl,content:x.content||""}))];save();render();}catch(e){alert("Không đọc được Drive URL. Có thể cần Apps Script public JSON.");}};
document.getElementById("driveApi").value=localStorage.getItem("tk_reader_drive_url")||"";
function openBook(b){current=b;const modal=document.getElementById("readerModal"), content=document.getElementById("readerContent");content.className="reader-content "+(localStorage.getItem("tk_reader_theme")||"paper");if(b.content)content.innerHTML=`<h2>${b.title}</h2><p>${String(b.content).replace(/\n/g,"<br>")}</p>`;else if(["jpg","jpeg","png","webp"].includes(b.type))content.innerHTML=`<h2>${b.title}</h2><img src="${b.url}">`;else if(b.type==="pdf")content.innerHTML=`<h2>${b.title}</h2><iframe src="${b.url}" style="width:100%;height:78vh;border:0"></iframe>`;else content.innerHTML=`<h2>${b.title}</h2><p>File này sẽ mở bằng liên kết bên ngoài.</p><p><a href="${b.url}" target="_blank">Mở file</a></p>`;modal.classList.remove("hidden");const pos=localStorage.getItem("tk_reader_pos_"+b.title);if(pos)setTimeout(()=>content.scrollTop=Number(pos),200);}
document.getElementById("closeReader").onclick=()=>document.getElementById("readerModal").classList.add("hidden");document.getElementById("themeSelect").onchange=e=>{localStorage.setItem("tk_reader_theme",e.target.value);document.getElementById("readerContent").className="reader-content "+e.target.value;};document.getElementById("savePos").onclick=()=>{if(current){localStorage.setItem("tk_reader_pos_"+current.title,document.getElementById("readerContent").scrollTop);alert("Đã lưu vị trí đọc.");}};load();